"""login roles approval guardrails observability usage cost

Revision ID: 23181e6d03b1
Revises: 5e66bb87e57f
Create Date: 2026-09-01 23:30:50.941998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.models


# revision identifiers, used by Alembic.
revision: str = '23181e6d03b1'
down_revision: Union[str, Sequence[str], None] = '5e66bb87e57f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_pricing',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_price_micros_per_1k', sa.Integer(), nullable=False),
    sa.Column('output_price_micros_per_1k', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_pricing_provider_model', 'model_pricing', ['provider', 'model', 'effective_from'], unique=False)
    op.create_table('guardrail_events',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.models.GUID(), nullable=False),
    sa.Column('session_id', app.db.models.GUID(), nullable=True),
    sa.Column('message_id', app.db.models.GUID(), nullable=True),
    sa.Column('turn_id', sa.String(length=64), nullable=True),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_guardrail_events_session_id', 'guardrail_events', ['session_id'], unique=False)
    op.create_index('ix_guardrail_events_tenant_id', 'guardrail_events', ['tenant_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('user_id', app.db.models.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.models.GUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_tokens_tenant_id', 'refresh_tokens', ['tenant_id'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('traces',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.models.GUID(), nullable=False),
    sa.Column('session_id', app.db.models.GUID(), nullable=True),
    sa.Column('turn_id', sa.String(length=64), nullable=False),
    sa.Column('langfuse_trace_id', sa.String(length=64), nullable=True),
    sa.Column('route', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_traces_session_id', 'traces', ['session_id'], unique=False)
    op.create_index('ix_traces_tenant_id', 'traces', ['tenant_id'], unique=False)
    op.create_table('usage_daily_rollups',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.models.GUID(), nullable=False),
    sa.Column('day', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_micros', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'day', 'provider', 'model', name='uq_usage_rollup_tenant_day_provider_model')
    )
    op.create_index('ix_usage_daily_rollups_tenant_id', 'usage_daily_rollups', ['tenant_id'], unique=False)
    op.create_table('user_approvals',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('user_id', app.db.models.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.models.GUID(), nullable=True),
    sa.Column('decided_by_user_id', app.db.models.GUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_approvals_user_id', 'user_approvals', ['user_id'], unique=False)
    op.create_table('model_calls',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.models.GUID(), nullable=False),
    sa.Column('trace_id', app.db.models.GUID(), nullable=True),
    sa.Column('session_id', app.db.models.GUID(), nullable=True),
    sa.Column('user_id', app.db.models.GUID(), nullable=True),
    sa.Column('call_type', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('used_fallback', sa.Boolean(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_micros', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_calls_tenant_created', 'model_calls', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_model_calls_tenant_id', 'model_calls', ['tenant_id'], unique=False)
    op.create_index('ix_model_calls_trace_id', 'model_calls', ['trace_id'], unique=False)
    op.create_table('trace_events',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('trace_id', app.db.models.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.models.GUID(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trace_events_trace_id', 'trace_events', ['trace_id'], unique=False)
    # server_default on these two ADD COLUMN ... NOT NULL statements backfills
    # any pre-existing rows at migration time (Postgres requires a value for
    # every existing row when a new column is added NOT NULL); the model-level
    # Python default ("member" / "pending") still governs every INSERT from
    # here on, this default only exists for rows that predate this migration.
    op.add_column('user_tenants', sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('user_tenants', sa.Column('invited_by_user_id', app.db.models.GUID(), nullable=True))
    op.alter_column('user_tenants', 'status', server_default=None)
    op.create_index('ix_user_tenants_tenant_status', 'user_tenants', ['tenant_id', 'status'], unique=False)
    op.create_foreign_key(None, 'user_tenants', 'users', ['invited_by_user_id'], ['id'])
    op.add_column('users', sa.Column('platform_role', sa.String(length=20), nullable=False, server_default='user'))
    op.add_column('users', sa.Column('approval_status', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('users', sa.Column('approved_by_user_id', app.db.models.GUID(), nullable=True))
    op.add_column('users', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'platform_role', server_default=None)
    op.alter_column('users', 'approval_status', server_default=None)
    op.create_index('ix_users_approval_status', 'users', ['approval_status'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['approved_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index('ix_users_approval_status', table_name='users')
    op.drop_column('users', 'approved_at')
    op.drop_column('users', 'approved_by_user_id')
    op.drop_column('users', 'approval_status')
    op.drop_column('users', 'platform_role')
    op.drop_constraint(None, 'user_tenants', type_='foreignkey')
    op.drop_index('ix_user_tenants_tenant_status', table_name='user_tenants')
    op.drop_column('user_tenants', 'invited_by_user_id')
    op.drop_column('user_tenants', 'status')
    op.drop_index('ix_trace_events_trace_id', table_name='trace_events')
    op.drop_table('trace_events')
    op.drop_index('ix_model_calls_trace_id', table_name='model_calls')
    op.drop_index('ix_model_calls_tenant_id', table_name='model_calls')
    op.drop_index('ix_model_calls_tenant_created', table_name='model_calls')
    op.drop_table('model_calls')
    op.drop_index('ix_user_approvals_user_id', table_name='user_approvals')
    op.drop_table('user_approvals')
    op.drop_index('ix_usage_daily_rollups_tenant_id', table_name='usage_daily_rollups')
    op.drop_table('usage_daily_rollups')
    op.drop_index('ix_traces_tenant_id', table_name='traces')
    op.drop_index('ix_traces_session_id', table_name='traces')
    op.drop_table('traces')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_tenant_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_guardrail_events_tenant_id', table_name='guardrail_events')
    op.drop_index('ix_guardrail_events_session_id', table_name='guardrail_events')
    op.drop_table('guardrail_events')
    op.drop_index('ix_model_pricing_provider_model', table_name='model_pricing')
    op.drop_table('model_pricing')
    # ### end Alembic commands ###
