"""initial schema

Revision ID: 5e66bb87e57f
Revises: 
Create Date: 2026-08-25 19:34:05.772074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.models


# revision identifiers, used by Alembic.
revision: str = '5e66bb87e57f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auth_identities',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('user_id', app.db.models.GUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_auth_identities_provider_subject')
    )
    op.create_index('ix_auth_identities_user_id', 'auth_identities', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.models.GUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('chunk_hashes', sa.JSON(), nullable=False),
    sa.Column('blocks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_tenant_id', 'documents', ['tenant_id'], unique=False)
    op.create_table('hitl_requests',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.models.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('session_id', app.db.models.GUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('deck_spec', sa.JSON(), nullable=True),
    sa.Column('skill_id', sa.String(length=255), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('downloadable_artifacts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hitl_requests_tenant_id', 'hitl_requests', ['tenant_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.models.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('memory_state', sa.JSON(), nullable=True),
    sa.Column('pending_skill_run', sa.JSON(), nullable=True),
    sa.Column('turn_checkpoint', sa.JSON(), nullable=True),
    sa.Column('pending_deck_builder', sa.JSON(), nullable=True),
    sa.Column('last_deck_spec', sa.JSON(), nullable=True),
    sa.Column('checkpoints', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_tenant_id', 'sessions', ['tenant_id'], unique=False)
    op.create_table('skill_packages',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('output', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_skill_packages_tenant_id', 'skill_packages', ['tenant_id'], unique=False)
    op.create_table('skill_runs',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.models.GUID(), nullable=False),
    sa.Column('skill_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=True),
    sa.Column('output_paths', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('used_fallback', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_skill_runs_tenant_id', 'skill_runs', ['tenant_id'], unique=False)
    op.create_table('user_tenants',
    sa.Column('user_id', app.db.models.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.models.GUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tenant_id')
    )
    op.create_index('ix_user_tenants_tenant_id', 'user_tenants', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('session_id', app.db.models.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.models.GUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_session_id', 'messages', ['session_id'], unique=False)
    op.create_index('ix_messages_tenant_id', 'messages', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_tenant_id', table_name='messages')
    op.drop_index('ix_messages_session_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_user_tenants_tenant_id', table_name='user_tenants')
    op.drop_table('user_tenants')
    op.drop_index('ix_skill_runs_tenant_id', table_name='skill_runs')
    op.drop_table('skill_runs')
    op.drop_index('ix_skill_packages_tenant_id', table_name='skill_packages')
    op.drop_table('skill_packages')
    op.drop_index('ix_sessions_tenant_id', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_hitl_requests_tenant_id', table_name='hitl_requests')
    op.drop_table('hitl_requests')
    op.drop_index('ix_documents_tenant_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_auth_identities_user_id', table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_table('users')
    op.drop_table('tenants')
    # ### end Alembic commands ###
