"""drop sessions and messages for redis, documents content to b2_key

Revision ID: 681b4ad4b4af
Revises: 23181e6d03b1
Create Date: 2026-09-02 00:27:12.373811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '681b4ad4b4af'
down_revision: Union[str, Sequence[str], None] = '23181e6d03b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: this migration is only safe to run as-is against an empty
    # `documents` table (true for every environment this app has run in so
    # far — see docs/database.md). A deployment with existing document rows
    # would need `b2_key` added nullable first, a backfill step that
    # actually uploads each row's `content` to B2 and records the resulting
    # key, and only then a NOT NULL — dropping `content` here would
    # otherwise discard document text with no B2 object ever created for it.
    # ### commands auto generated by Alembic - please adjust! ###
    # Reordered from autogenerate's raw output: messages.session_id FKs into
    # sessions, so messages must drop first — the generator doesn't sequence
    # drops by dependency, it emitted sessions before messages and asyncpg
    # (unlike a DROP ... CASCADE) refuses that order outright.
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_sessions_tenant_id'), table_name='sessions')
    op.drop_table('sessions')
    op.add_column('documents', sa.Column('b2_key', sa.String(length=512), nullable=False))
    op.drop_column('documents', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Reordered same as upgrade(): sessions must exist before messages can
    # reference it via FK — the generator emitted messages first.
    op.add_column('documents', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'b2_key')
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('memory_state', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('pending_skill_run', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('turn_checkpoint', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('pending_deck_builder', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_deck_spec', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('checkpoints', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('sessions_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sessions_pkey'))
    )
    op.create_index(op.f('ix_sessions_tenant_id'), 'sessions', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('seq', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('messages_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    # ### end Alembic commands ###
